; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[common]
device_name = myesp32 ;change this if you have multiple devices on your network!

[env]
default_envs = esp32_ota, esp32_serial

platform = espressif32
board = esp32dev
framework = arduino
; upload_speed = 115200
monitor_speed = 115200
build_flags = 
    '-D DEBUG'
    '-D DEVICE_NAME="${common.device_name}"'
lib_deps =
  jandrassy/TelnetStream

[env:esp32_ota]
; if not find device on Network this should be automatically fail back!
; otherwise it will set a flag so the serial upload can be cancle!
upload_protocol = espota
upload_port = ${common.device_name}.local  ; or dummy value
extra_scripts = scripts/resolve_ota.py

; pio device monitor -e esp32dev
; Wireless monitor setup, note that you need to press enter to reconnect
monitor_port = socket://${common.device_name}.local:23
monitor_filters = direct, time, send_on_enter
monitor_echo = yes

[env:esp32_serial]
; failback serial upload!
extra_scripts = scripts/prevent_uart.py
